# **Diplomado IA: Aprendizaje Profundo I - Parte 1**. <br> Práctico Clase 7: PyTorch
---
---

**Profesores:**
- Alain Raymond
- Gabriel Sepúlveda
- Miguel Fadic
- Álvaro Soto

**Ayudante:**
- Andrés Villa
---
---

El siguiente práctico se debe realizar de forma individual. El formato de entregar es el **archivo .ipynb con todas las celdas ejecutadas**. Las secciones donde se planteen preguntas de forma explícita, deben ser respondida en celdas de texto, y no se aceptará solo el _output_ de una celda de código como respuesta.

**Nombre alumno:**

El siguiente práctico contendrá 1 o más actividades a realizar. Algunas actividades corresponderán a escribir código y otras a responder preguntas.

Antes de responder, se recomienda **fuertemente** revisar las secciones previas donde se desarrollan los ejemplos, dado que algunas de las actividades pueden ser completadas reutilizando el mismo código.


---
**IMPORTANTE:** habrá un bonus de 1 décima para todos aquellos alumnos/as que muestren buen orden en sus respuestas (esto aplica a legibilidad de código, buena redacción, formalidad, organización del jupyter notebook, seguimiento de instrucciones, etc). El criterio lo pondrá cada ayudante corrector. La nota máxima obtenible en el laboratorio es 7.0

## El Tensor: la unidad fundamental.

Los tensores son el elemento fundamental con que trabajarán nuestras redes profundas. Un tensor es simplemente una matriz de n-dimensiones.

* En **imágenes**, usamos tensores de 4 dimensiones: 3 dimensiones (alto, ancho y color) más una cuarta dimensión asociada a los elementos del batch.

* Cuando trabajamos con **texto** podemos tener tensores en 3 dimensiones (dimensión de embedding, palabras y batch).

* Si trabajamos con **videos** tenemos que agregar otra dimensión para el tiempo. En fin, todos estos datos distintos al final se representan como matrices de números en 3, 4 ó 5 dimensiones distintas.

Pytorch representa los tensores via la clase torch.Tensor. Todas las redes neuronales que hagamos requieren tensores para poder trabajar. Nuestros datasets no servirán de nada si no podemos transformarlos en tensores que podamos ocupar con nuestras redes. Si han trabajado con *ndarray* de Numpy la forma de ocuparlos es muy similar. Veamos un tensor de ejemplo de 3 dimensiones: ancho, alto y batch.

In [1]:
import torch

batch_dim = 2
ancho = 4
alto = 3
tensor_ejemplo = torch.randn((batch_dim, ancho, alto)).float() # Tensor aleatorio
print("El tensor es: {}\n".format(tensor_ejemplo))
print("La forma del tensor es: {}".format(tensor_ejemplo.shape))
print("El tipo del tensor es: {}".format(type(tensor_ejemplo)))

El tensor es: tensor([[[-1.1938,  0.2638,  0.5017],
         [ 0.5649, -1.1356,  0.1043],
         [-0.2367,  1.1050, -0.1637],
         [-0.7329,  0.5200, -0.3071]],

        [[-0.4596, -0.6214, -1.7263],
         [-0.1324, -1.1799, -0.2345],
         [-0.0471,  0.0234,  1.0838],
         [-0.3815, -1.1738,  0.1757]]])

La forma del tensor es: torch.Size([2, 4, 3])
El tipo del tensor es: <class 'torch.Tensor'>


Crear un tensor desde un arreglo de Python es sencillo:

In [2]:
arreglo = [[1, 2, 3], [4, 5, 6]]
tensor_desde_arreglo = torch.tensor(arreglo)
print(tensor_desde_arreglo, tensor_desde_arreglo.shape)
tensor_desde_arreglo2 = torch.tensor(arreglo)
suma = tensor_desde_arreglo +  tensor_desde_arreglo2
print(suma)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


Uno trabaja los tensores de la misma manera que cualquier otra variable numérica en Python. Se pueden, sumar y restar sin problema. La multiplicación por escalares no supone problema y la multiplicación de tensores también está soportada.



In [3]:
tensor_1 = torch.randn((10,2,3))
tensor_2 = torch.randn((10,2,3))

tensor_3 = tensor_1*tensor_2
print(tensor_1.shape)
print(tensor_2)
print(tensor_3)

torch.Size([10, 2, 3])
tensor([[[-0.4274, -1.1154,  1.5330],
         [ 0.0470, -0.1978, -0.9705]],

        [[-2.0724,  1.0770, -0.5770],
         [-1.1348,  1.2089,  0.4468]],

        [[ 2.3965, -0.1479,  0.9757],
         [ 1.0144, -0.4383, -1.5724]],

        [[ 1.2682,  0.5602,  1.2738],
         [-0.2718, -0.1209, -1.1411]],

        [[-1.1744, -0.8583,  0.2714],
         [-1.2666, -0.5749,  0.1824]],

        [[-1.1969,  0.4472, -1.4157],
         [ 0.0261, -2.3975,  0.7984]],

        [[ 0.5255, -0.7379,  1.1456],
         [ 0.9198,  0.7047,  0.1200]],

        [[ 0.0668, -0.1761,  0.5182],
         [-1.8094, -0.0041,  0.8630]],

        [[ 1.3385,  0.9416, -0.3940],
         [ 0.4485,  0.1031, -0.7065]],

        [[-0.3970, -1.4549,  1.1717],
         [ 1.1373, -1.3932, -1.1643]]])
tensor([[[ 0.1049, -2.0399,  1.0968],
         [-0.0112, -0.2274,  0.2566]],

        [[ 0.2795, -0.1035,  1.2240],
         [-0.7787, -1.0384,  0.1291]],

        [[ 1.0017, -0.0748, -1.1270],
   

Podemos indexarlos:

In [4]:
print(tensor_1.shape)

lista = [1, 2, 3,4]

print(lista[0:2])

tensor_indexado = tensor_1[0:2,0,0]
print(tensor_indexado, tensor_indexado.shape)

torch.Size([10, 2, 3])
[1, 2]
tensor([-0.2455, -0.1349]) torch.Size([2])


In [5]:
torch.randn(10, 3, 64, 64).shape

torch.Size([10, 3, 64, 64])

#### Sobre la dimensión batch

La dimensión de batch es importante pues es la que nos permite poder entrenar de forma paralela en nuestras GPUs. El estándar de Pytorch es que ésta es la primera dimensión de nuestros tensores siempre. Aunque solo evaluar un elemento en nuestra red, este debe tener una dimensión de batch en su primer lugar o sino no funcionará. También es necesario mencionar que Pytorch espera siempre que la dimensión del canal vaya antes que las dimensiones de ancho y alto en imágenes.

### Sobre el dispositivo asociado

Los tensores son procesados por la CPU o por una GPU. Como quizás hemos escuchado antes, sabemos que parte de la explosión de Deep Learning viene por la disponibilidad de GPUs cada vez más poderosas. Para poder trabajar en GPU un tensor tenemos que hacer lo siguiente:

In [ ]:
tensor_nuevo = torch.randn((1,2,3))     # Por defecto el tensor está en CPU
tensor_nuevo_gpu = tensor_nuevo.cuda()  # Creé una copia de tensor_nuevo en GPU!
otra_forma = tensor_nuevo.to("cuda")    # Creé otra copia de tensor_nuevo en GPU!
print(otra_forma)


tensor([[[ 0.3019,  1.3206, -0.5961],
         [-0.6800, -0.2182, -1.8108]]], device='cuda:0')


## Definición del Modelo
Como vimos en el laboratorio pasado, definir un modelo de aprendizaje profundo consiste en definir una nueva clase que herede de torch.nn.Module.

Esta clase debe implementar dos métodos para funcionar como un modelo válido en Pytorch:

* Método \_\_init\_\_(self): el constructor de la clase. Aquí es donde usualmente definiremos todos los elementos arquitéctonicos de nuestra red. Aquí definiremos que capas tendrá, qué funciones de activación, funciones de pooling, etc.

* Método forward(self, input): define las conexiones entre capas del modelo, o cómo debe fluir la información que entra en él. Debe retornar un tensor.

### Elementos arquitectónicos

Todos estos elementos están definidos en el paquete torch.nn (de Neural Networks). Todos derivan de la clase torch.nn.Module.

* **Linear:** capa lineal. Toma como parámetros las cantidades de neuronas de entrada y de salida.
* **Conv1d, Conv2d, Conv3d**: capas convolucionales de 1, 2 y 3 dimensiones respectivamente. Definidas por el tamaño del kernel que ocupan, el *stride*, filtros de entrada y de salida.
* **ReLU**: función de activación. No tiene parámetros.
* **Sigmoid**: función de activación. No tiene parámetros.
* **Softmax**: capa que transforma el output en una distribución de probabilidad. Parámetro es sobre la o las dimensiones que se aplica.
* **MaxPool1d, MaxPool2d, MaxPool3d**: Funciones de pooling en 1,2 y 3 dimensiones respectivamente.
* **Dropout**: capa que deja en 0 neuronas con probabilidad $p$. Parámetro: $p$.
* **BatchNorm2d**: capa que normaliza el input de acuerdo a una media y varianza aprendidas.
* **LayerNorm**:
* **Sequential**: es un agrupador de Módulos. Se encarga de que la información fluya de forma secuencial entre los módulos que contiene.

In [6]:
import torch
from torch.nn import Linear, ReLU, Sigmoid, Sequential, Softmax, BatchNorm1d, BatchNorm2d, Dropout, LayerNorm

tensor_prueba = torch.randn((3, 5))

print(tensor_prueba, tensor_prueba.shape)

# Capa Lineal que va de 5 dimensiones a 8
capa_lineal = Linear(5, 8)
tensor_nuevo = capa_lineal(tensor_prueba)
print("Tensor después de Capa Lineal:")
print(tensor_nuevo, tensor_nuevo.shape)

tensor([[ 1.6242, -1.4484, -0.7869, -1.3575, -0.3389],
        [-0.0597, -1.0161, -0.9935,  0.5773,  0.1553],
        [ 0.4160,  1.2555, -2.5687,  0.4599, -0.4211]]) torch.Size([3, 5])
Tensor después de Capa Lineal:
tensor([[-0.3925, -1.0241, -1.5916, -0.3037, -0.8452, -0.4214, -1.1762,  0.4189],
        [-0.3703,  0.0737, -0.3450, -0.1637, -0.3950,  0.5478, -0.3754,  0.2379],
        [ 0.8189, -0.6418,  0.1086, -0.0366,  0.2350, -0.4037, -0.6229, -0.3475]],
       grad_fn=<AddmmBackward0>) torch.Size([3, 8])


In [7]:
# Funciones de Activación
# ReLU
relu = ReLU()
print("Antes de ReLU: ")
print(tensor_prueba)
print("Después de ReLU: ")
print(relu(tensor_prueba))

Antes de ReLU: 
tensor([[ 1.6242, -1.4484, -0.7869, -1.3575, -0.3389],
        [-0.0597, -1.0161, -0.9935,  0.5773,  0.1553],
        [ 0.4160,  1.2555, -2.5687,  0.4599, -0.4211]])
Después de ReLU: 
tensor([[1.6242, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5773, 0.1553],
        [0.4160, 1.2555, 0.0000, 0.4599, 0.0000]])


In [8]:
# Sigmoid
s = Sigmoid()
print("Antes de Sigmoid: ")
print(tensor_prueba)
print("Después de Sigmoid: ")
print(s(tensor_prueba))

Antes de Sigmoid: 
tensor([[ 1.6242, -1.4484, -0.7869, -1.3575, -0.3389],
        [-0.0597, -1.0161, -0.9935,  0.5773,  0.1553],
        [ 0.4160,  1.2555, -2.5687,  0.4599, -0.4211]])
Después de Sigmoid: 
tensor([[0.8354, 0.1902, 0.3128, 0.2046, 0.4161],
        [0.4851, 0.2658, 0.2702, 0.6405, 0.5387],
        [0.6025, 0.7782, 0.0712, 0.6130, 0.3963]])


In [9]:
# Softmax
soft = Softmax(dim=1)
print("Antes de Softmax: ")
print(tensor_prueba)
print("Después de Softmax: ")
soft_tensor = soft(tensor_prueba)
print(soft_tensor)
print(soft_tensor.sum(dim=0))

Antes de Softmax: 
tensor([[ 1.6242, -1.4484, -0.7869, -1.3575, -0.3389],
        [-0.0597, -1.0161, -0.9935,  0.5773,  0.1553],
        [ 0.4160,  1.2555, -2.5687,  0.4599, -0.4211]])
Después de Softmax: 
tensor([[0.7535, 0.0349, 0.0676, 0.0382, 0.1058],
        [0.2038, 0.0783, 0.0801, 0.3853, 0.2526],
        [0.2065, 0.4780, 0.0104, 0.2157, 0.0894]])
tensor([1.1637, 0.5912, 0.1581, 0.6392, 0.4478])


In [10]:
# Sequential
# Unamos pasos
seq = Sequential(capa_lineal, relu, soft)
tensor_final = seq(tensor_prueba)
print("Aplicando Sequential: ")
print(tensor_final, tensor_final.shape)

Aplicando Sequential: 
tensor([[0.1174, 0.1174, 0.1174, 0.1174, 0.1174, 0.1174, 0.1174, 0.1784],
        [0.1102, 0.1186, 0.1102, 0.1102, 0.1102, 0.1906, 0.1102, 0.1398],
        [0.2351, 0.1037, 0.1155, 0.1037, 0.1311, 0.1037, 0.1037, 0.1037]],
       grad_fn=<SoftmaxBackward0>) torch.Size([3, 8])


In [17]:
# Dropout
drop = Dropout(p=0.1) # con probabilidad de dejar en 0 de 0.5.

tensor_dropout = drop(tensor_prueba)
print(tensor_dropout)

tensor([[ 1.8047, -1.6093, -0.8743, -1.5083, -0.3766],
        [-0.0663, -1.1291, -1.1039,  0.6415,  0.1725],
        [ 0.4622,  1.3950, -2.8541,  0.5110, -0.4679]])


In [18]:
# Batch Normalization 1d
tensor_lineal = 100*torch.randn((3, 5))  # Una imagen con varianza alta
bn = BatchNorm1d(5, momentum=None)
print("La media de los vectores originales por dimensión es: {}".format(tensor_lineal.mean(dim=[0])))
print("La varianza de los vectores originales por dimensión es: {}".format(tensor_lineal.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_lineal)

print("La media por dimensión del resultado es: {}".format(tensor_bn.mean(dim=[0])))
print("La varianza por dimensión del resultado es: {}".format(tensor_bn.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de los vectores originales por dimensión es: tensor([ 25.8616, -74.8571,   0.7456,  11.3224, -14.8267])
La varianza de los vectores originales por dimensión es: tensor([ 8383.7021, 13947.2715,  1898.5669,  3095.4729,  8237.3730])
Las medias por dimensión de BN inicialmente son: tensor([0., 0., 0., 0., 0.])
Las varianzas por dimensión de BN inicialmente son: tensor([1., 1., 1., 1., 1.])
La media por dimensión del resultado es: tensor([-1.9868e-08,  3.9736e-08,  0.0000e+00,  0.0000e+00, -3.9736e-08],
       grad_fn=<MeanBackward1>)
La varianza por dimensión del resultado es: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<VarBackward0>)
Las medias por dimensión de BN ahora son: tensor([ 25.8616, -74.8571,   0.7456,  11.3224, -14.8267])
Las varianzas por dimensión de BN ahora son: tensor([12575.5527, 20920.9062,  2847.8503,  4643.2095, 12356.0605])
weight Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0.

In [20]:
# Batch Normalization 2d
tensor_imagenes = 20*torch.randn((4, 3, 2, 2))  # Una imagen con varianza alta
bn = BatchNorm2d(3, momentum = None)                             # 3 es el número de canales


print("La media de las imágenes originales por canal es: {}".format(tensor_imagenes.mean(dim=[0,2,3])))
print("La varianza de las imágenes originales por canal es: {}".format(tensor_imagenes.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_imagenes)
print("La media por canal es: {}".format(tensor_bn.mean(dim=[0,2,3])))
print("La varianza por canal es: {}".format(tensor_bn.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de las imágenes originales por canal es: tensor([ 3.6324,  8.0519, -1.4734])
La varianza de las imágenes originales por canal es: tensor([409.2384, 429.5763, 163.2007])
Las medias por canal de BN inicialmente son: tensor([0., 0., 0.])
Las varianzas por canal de BN inicialmente son: tensor([1., 1., 1.])
La media por canal es: tensor([-3.7253e-09,  0.0000e+00,  0.0000e+00], grad_fn=<MeanBackward1>)
La varianza por canal es: tensor([1.0667, 1.0667, 1.0667], grad_fn=<VarBackward0>)
Las medias por canal de BN ahora son: tensor([ 3.6324,  8.0519, -1.4734])
Las varianzas por canal de BN ahora son: tensor([409.2385, 429.5763, 163.2007])
weight Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [21]:
# Layer Normalization
tensor_lineal = 100*torch.randn((20, 100))  # Una imagen con varianza alta
ln = LayerNorm(100, eps=0 ,elementwise_affine=True) # elementwise_affine determina si tiene parámetros aprendibles o no.
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))
for n, p in ln.named_parameters():
  print(n,p)

# Cambiemos la media y desviación estándar a mano
new_weight1 = torch.ones(100) * 100.0
new_weight2 = torch.ones(100) * 5.0
with torch.no_grad():
    ln.weight.copy_(new_weight1)
    ln.bias.copy_(new_weight2)

# evaluamos de nuevo sobre los mismos datos
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))

Media del resultado:  tensor([-4.7684e-09, -2.7418e-08,  4.7684e-09, -2.3842e-09,  5.9605e-09,
         9.5367e-09, -9.5367e-09, -9.5367e-09,  1.7881e-08,  2.3842e-09,
        -9.5367e-09,  7.1526e-09,  1.1921e-08,  3.2187e-08, -4.7684e-09,
         5.3644e-09,  1.1921e-08,  1.9073e-08, -1.6689e-08, -1.7881e-08],
       grad_fn=<MeanBackward1>)
Desviación estándar del resultado:  tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000], grad_fn=<StdBackward0>)
weight Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

### Revisitando AlexNet

In [22]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )



    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [23]:
m = MiAlexNet()

In [24]:
for n, p in m.named_parameters():
  print(n, p.shape)


conv1.0.weight torch.Size([96, 3, 11, 11])
conv1.0.bias torch.Size([96])
conv2.0.weight torch.Size([256, 96, 5, 5])
conv2.0.bias torch.Size([256])
conv3.0.weight torch.Size([384, 256, 3, 3])
conv3.0.bias torch.Size([384])
conv4.0.weight torch.Size([384, 384, 3, 3])
conv4.0.bias torch.Size([384])
conv5.0.weight torch.Size([256, 384, 3, 3])
conv5.0.bias torch.Size([256])
fc6.0.weight torch.Size([4096, 9216])
fc6.0.bias torch.Size([4096])
fc7.0.weight torch.Size([4096, 4096])
fc7.0.bias torch.Size([4096])
fc8.0.weight torch.Size([102, 4096])
fc8.0.bias torch.Size([102])


In [25]:
fotos_de_mentira = torch.randn(15, 3, 224, 224)

m(fotos_de_mentira).shape

torch.Size([15, 102])

## Manejo de Datos

En un problema normal de Machine Learning, usualmente la gestión de datos no era muy importante dado que los datasets en general son pequeños. Sin embargo, dados los volúmenes de datos que requieren los modelos de aprendizaje profundo, se vuelve difícil mantener los datos en memoria. Por esto, se requiere consumirlos de manera parcelada para poder ocuparlos con las restricciones de hardware que tenemos.

Pytorch resuelve el problema mediante dos abstracciones: las clases *Dataset* y *DataLoader*.

* La clase *Dataset* trabaja como una interfaz sencilla para acceder nuestros datos físicos.
* La clase *DataLoader* se encarga de agrupar los elementos de la clase *Dataset* en *batches* para pasarle a nuestro modelo.

Usualmente, el mayor trabajo reside en definir una clase Dataset apropiada para nuestro conjunto de datos. Por suerte, si queremos trabajar con ciertos conjuntos de datos estándar, Pytorch ya tiene definido estos datasets por nosotros.

Si no, lo único que tenemos que hacer es definir una clase que herede de torch.utils.data.Dataset y que implemente dos métodos:

* \_\_len(self)\_\_: método que devuelva el tamaño total del dataset.
* \_\_getitem\_\_(self, index): método que entregue un elemento particular del dataset dado un índice (index).

### Usar Datasets predefinidos

In [26]:
from torchvision.datasets import MNIST, CIFAR10

mnist_train = MNIST(root=".", train=True, download=True)
cifar = CIFAR10(root=".", train=True, download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 20.1MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 479kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.50MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 16.3MB/s]
100%|██████████| 170M/170M [00:05<00:00, 31.1MB/s]


In [27]:
len(mnist_train)

60000

Veamos un ejemplo del dataset.

In [28]:
mnist_train[459]

(<PIL.Image.Image image mode=L size=28x28>, 3)

Vemos que contiene dos elementos: el primero es una imagen en formato PIL y el segundo es la clase asociada a esa imagen (nuestro target o ground truth). La imagen se ve así:

In [29]:
from IPython.display import display     # Esto no es Pytorch, es solo una librería
                                        # para desplegar imágenes en Colab.
display(mnist_train[459][0])
#display(cifar[0][0])

Sin embargo, una imagen en formato PIL no es un tensor de Pytorch. Tenemos que hacer algo para transformarla! Por suerte para nosotros, Pytorch nos ofrece transformaciones estándar para imágenes, en particular, una para transformar imágenes PIL a tensores. Veamos cómo:

In [30]:
from torchvision.transforms import ToTensor
mnist_train = MNIST(root=".", train=True, download=True, transform=ToTensor())

In [31]:
mnist_train[459]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

Ahora nuestro Dataset automáticamente transforma las imágenes PIL a tensores de Pytorch!

### Crear un Dataset de ejemplo

Vamos a crear un Dataset para el conjunto de datos Flowers que vimos el laboratorio pasado.

In [32]:
!wget https://www.dropbox.com/s/q53g4cmpnvzhnhi/flowers.tar.gz -q --show-progress
!tar -xzf flowers.tar.gz

flowers.tar.gz      100%[===================>] 328.99M  60.3MB/s    in 4.9s    


In [33]:
from os import listdir
from os.path import join
from PIL import Image
import torch
from torchvision.transforms import Compose, ToTensor, Resize
class Flowers(torch.utils.data.Dataset):
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform
        self.imagenes = []       # Vincula el indice con un nombre de archivo
        self.imgs_to_class = []  # Vincula el indice con una clase
        self.imagenes, self.imgs_to_class = self.armar_indices(root)

    def armar_indices(self, root):
        n_classes = len(listdir(root)) # El número de carpetas es la cantidad de clases
        contador = 0
        lista_imagenes = []
        imgs_to_class = []
        for clase in listdir(root):
            directorio = join(root, clase)
            for archivo in listdir(directorio):
                lista_imagenes.append(archivo)
                contador+=1
                imgs_to_class.append(int(clase))

        return lista_imagenes, imgs_to_class

    def obtener_imagen(self, archivo):

        im = Image.open(archivo)
        return im

    def __getitem__(self, idx):

        nombre_archivo = self.imagenes[idx]
        clase = self.imgs_to_class[idx]
        ruta_img = join(self.root, str(clase))
        ruta_img = join(ruta_img, nombre_archivo)
        img = self.obtener_imagen(ruta_img)

        if self.transform is not None:
            img = self.transform(img)
        return img, clase

    def __len__(self):
        return len(self.imagenes)

In [34]:
transforms = Compose([Resize((224,224)), ToTensor()])
f = Flowers('flowers_dataset/train', transform=transforms)
print(f[0])

(tensor([[[0.1373, 0.1333, 0.1451,  ..., 0.1216, 0.1176, 0.0980],
         [0.1333, 0.1412, 0.1373,  ..., 0.1137, 0.1098, 0.0941],
         [0.1373, 0.1412, 0.1412,  ..., 0.0980, 0.1020, 0.1137],
         ...,
         [0.2941, 0.2706, 0.2431,  ..., 0.0510, 0.0549, 0.0510],
         [0.2549, 0.2431, 0.2314,  ..., 0.0431, 0.0471, 0.0431],
         [0.2431, 0.2353, 0.2353,  ..., 0.0392, 0.0431, 0.0314]],

        [[0.1294, 0.1255, 0.1373,  ..., 0.0902, 0.0980, 0.1020],
         [0.1255, 0.1333, 0.1294,  ..., 0.0941, 0.0980, 0.0941],
         [0.1294, 0.1333, 0.1333,  ..., 0.0941, 0.1020, 0.1098],
         ...,
         [0.2275, 0.2078, 0.1765,  ..., 0.0549, 0.0588, 0.0549],
         [0.2078, 0.1922, 0.1765,  ..., 0.0549, 0.0588, 0.0549],
         [0.2000, 0.1882, 0.1843,  ..., 0.0549, 0.0588, 0.0471]],

        [[0.1333, 0.1294, 0.1412,  ..., 0.1098, 0.1137, 0.1098],
         [0.1294, 0.1373, 0.1333,  ..., 0.1098, 0.1137, 0.1020],
         [0.1333, 0.1373, 0.1373,  ..., 0.1059, 0.1098, 0

In [35]:
len(f)

5687

### Iterar sobre los datos

Dado un Dataset, sea hecho por nosotros o uno predefinido, iterar sobre los datos es muy sencillo. Simplemente tenemos que crear un objeto DataLoader que toma como argumento el Dataset y definir el batch size con que queremos trabajar.


Este código iterará por todos los batches de ejemplos de nuestro dataset y parará cuando se acaben. Es decir, esto corre por una **época**.

In [36]:
from torch.utils.data import DataLoader
train_dl = DataLoader(f, batch_size=128, shuffle=True)

for n_batch, (x, target) in enumerate(train_dl):
    print("\rN_Batch: {} input: {}- Label:{}".format(n_batch, x.shape, target.shape), end="")

N_Batch: 44 input: torch.Size([55, 3, 224, 224])- Label:torch.Size([55])

### Optimización

¿Como obtenemos los pesos óptimos para nuestra red? Si recordamos nuestras clases anteriores debemos optimizar la función de pérdida para tratar de encontrar los parámetros de nuestra red que minimizan su valor.

Primero debemos definir la función de pérdida. Éstas están definidas en torch.nn también. Las usuales son:

* CrossEntropyLoss: Entropía Cruzada, mide la distancia entre dos distribuciones de probabilidad. La función de pérdida más común para problemas de clasificación.
* MSELoss: Error cuadrático medio. Pérdida usual en problemas de regresión.

Hay más para revisar en la documentación de Pytorch (https://pytorch.org/docs/stable/nn.html).

Dado el resultado de nuestra red y el ground truth que deberíamos predecir, la pérdida es:


In [37]:
from torch.nn import CrossEntropyLoss
funcion_perdida = CrossEntropyLoss()

In [38]:
loss = funcion_perdida(output, target) # No correr este código, va a dar error! Es un ejemplo!

NameError: name 'output' is not defined

Súper, tenemos la pérdida, ¿cómo calculamos los gradientes?

Para eso necesitamos un algoritmo de optimización. En el curso de Herramientas verán los algoritmos en detalle, pero les debería sonar Stochastic Gradient Descent (SGD), que es el algoritmo estándar de optimización. Este ya está implementado por el paquete torch.optim.


In [39]:
from torch.optim import SGD, Adam

optimizer = SGD(model.parameters())     # Vinculamos el recién creado optimizador
                                        # a los parámetros de nuestro modelo

NameError: name 'model' is not defined

Esto por sí solo todavía no hace nada. El optimizador va a ir gestionando los gradientes que le llegan a cada parámetro de nuestro modelo. Actualizará los valores de los parámetros de acuerdo al algoritmo de optimización que implemente.

Pero para gestionar gradientes tiene que sacarlos de alguna parte. ¡Esto lo hace backpropagation! Por suerte es muy fácil calcularlos en Pytorch.

In [40]:
loss.backward()                         # ¡Backpropagation! Eso es todo.

NameError: name 'loss' is not defined

Luego uniendo todas las piezas, en cada iteración de nuestro algoritmo de entrenamiento haremos lo siguiente:

In [ ]:
optimizer.zero_grad()                   # 1. Hacemos cero los gradientes de los parámetros
output = model(input)                   # 2. Propagamos los datos de entrada por nuestro modelo
loss = funcion_perdida(output, target)  # 3. Cálculamos la pérdida
loss.backward()                         # 4. ¡Backpropagation! Calculamos los gradientes
                                        # para nuestros parámetros. ¡Los gradientes
                                        # dejan de ser 0!
optimizer.step()                        # 5. Actualizamos los parámetros de nuestro modelo

## Evaluación de Rendimiento

¿Cómo evaluamos el rendimiento? En problemas de clasificación lo que usualmente haremos es comparar el ground truth respecto a lo que predecimos. ¿Qué es lo que predecimos? Usualmente será la clase de mayor valor en su salida entre las N clases que tenemos que predecir. Esto lo podemos hacer usando la función *argmax* de Pytorch.

In [ ]:
output = model(input)                       # Tensor de salida de tamaño (batch_size, n_clases)
preds = output.argmax(dim=1)                # Nos quedamos con el índice que tiene mayor valor
                                            # entre las N clases.
n_correctas = (preds == targets).sum()      # preds == targets entrega un tensor de 1s o 0s.
total = targets.shape[0]                    # Total de ejemplos
acc = n_correctas/total                     # Accuracy es correctas/total

## Uniendo todo

Vamos a unir todos estos componentes para armar un flujo de entrenamiento completo:

In [49]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )


    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [42]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet

model = MiAlexNet()
#Descomentar esto para ocupar modelo preentrenado
#model = alexnet(pretrained=True)
#model.features.requires_grad_(False)
#model.classifier = nn.Sequential(
#            nn.Dropout(),
#            nn.Linear(256 * 6 * 6, 4096),
#            nn.ReLU(inplace=True),
#            nn.Dropout(),
#            nn.Linear(4096, 4096),
#            nn.ReLU(inplace=True),
#            nn.Linear(4096, 102),
#        )

model = model.cuda()    # Lo enviamos para que se ejecute en GPU
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms) # Creamos

n_epochs = 10
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)

optimizer = Adam(model.parameters(), lr=0.001)    # Creamos nuestro optimizador
loss_function = CrossEntropyLoss()      # Creamos la función de pérdida

model.train()                           # Dejamos el modelo en modo de entrenamiento
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:          # Iteramos sobre nuestros datos
        # Inicio de la iteración
        optimizer.zero_grad()           # Hacemos cero los gradientes de nuestros parámetros
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida
        loss.backward()                          # Backpropagation
        optimizer.step()                         # Actualizamos parámetros

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rEpoca {}: Loss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(epoch,
                                                                                      loss,
                                                                                      total_correctas,
                                                                                      total_muestras,
                                                                                      100*accuracy), end="")
    print("")

Epoca 1: Loss: 4.44 Correctas: 152.0 Total: 5687.0 Accuracy: 2.67%
Epoca 2: Loss: 4.49 Correctas: 176.0 Total: 5687.0 Accuracy: 3.09%
Epoca 3: Loss: 3.85 Correctas: 363.0 Total: 5687.0 Accuracy: 6.38%
Epoca 4: Loss: 3.73 Correctas: 453.0 Total: 5687.0 Accuracy: 7.97%
Epoca 5: Loss: 3.45 Correctas: 591.0 Total: 5687.0 Accuracy: 10.39%
Epoca 6: Loss: 3.43 Correctas: 737.0 Total: 5687.0 Accuracy: 12.96%
Epoca 7: Loss: 3.20 Correctas: 846.0 Total: 5687.0 Accuracy: 14.88%
Epoca 8: Loss: 3.44 Correctas: 1084.0 Total: 5687.0 Accuracy: 19.06%
Epoca 9: Loss: 2.99 Correctas: 1260.0 Total: 5687.0 Accuracy: 22.16%
Epoca 10: Loss: 2.54 Correctas: 1486.0 Total: 5687.0 Accuracy: 26.13%


### Evaluando el modelo en el conjunto de Test

In [43]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet
ds_test = Flowers("flowers_dataset/test", transform=transforms)
test_dl = DataLoader(ds_test, batch_size=1024)

total_correctas = 0.0
total_muestras = 0.0

model.eval()
for x, target in test_dl:          # Iteramos sobre nuestros datos
    # Inicio de la iteración
                      # Dejamos el modelo en modo evaluación
    with torch.no_grad():               # No se calculará información de gradientes
                                        # en el código de más abajo.
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rLoss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(loss,
                                                                                total_correctas,
                                                                                total_muestras,
                                                                                100*accuracy), end="")

Loss: 2.82 Correctas: 476.0 Total: 1738.0 Accuracy: 27.39%

## Guardar el Modelo

Una vez entrenado, querremos guardar el modelo para no tener que reentrenarlo cada vez que lo queramos usar. Esto es fácil de hacer en Pytorch.

La forma más eficiente y correcta es simplemente guardar los pesos. Estos se encuentran en una estructura llamada *'state_dict'* en el modelo. Una vez guardados, para recuperar nuestro modelo, tenemos que crear un modelo nuevo y ocupar el método *'load_state_dict'* para cargar los pesos.

In [44]:
torch.save(model.state_dict(), "MNIST/pesos_modelo_entrenado.pth") # Guardamos a disco los pesos

modelo = MiAlexNet()                                # Modelo con pesos aleatorios
pesos = torch.load("MNIST/pesos_modelo_entrenado.pth") # Cargamos los pesos a una variable
modelo.load_state_dict(pesos)                       # ¡Los pesos se encuentran
                                                    # cargados en el modelo!

<All keys matched successfully>

## Actividades

1. Entrene el modelo MiAlexNet por 10 épocas. ¿Qué resultados obtiene en train y test?
2. Modifique el modelo MiAlexNet para que haya una capa de Dropout antes de FC6 y FC7. Entrénelo por 10 épocas. ¿Ve cambios en el rendimiento del modelo?
3. Agregue capas de Batch Normalization (*BatchNorm2d*) antes de Conv3, Conv4 y Conv5. Entrene el modelo por 10 épocas. ¿Ve algún cambio en el entrenamiento?
4. Ocupe el modelo preentrenado en ImageNet de AlexNet. Entrénelo por 10 épocas. ¿Afecta en algo en rendimiento? Para ocupar el modelo preentrenado reemplace esta línea del código de entrenamiento:

In [45]:
model = MiAlexNet()     # Creamos el modelo

Por estas otras líneas:

In [46]:
from torchvision.models import alexnet

model = alexnet(pretrained=True)
model.features.requires_grad_(False)
model.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, 102),
        )

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth


100%|██████████| 233M/233M [00:01<00:00, 194MB/s]


### Respuestas Actividad

Por favor, sus respuestas a la actividad acá. No modificar el código anterior.

**Actividad 1**

In [48]:
# Ponga su código aquí

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.transforms import Compose, Resize, ToTensor

# Datos
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms)
ds_test  = Flowers("flowers_dataset/test",  transform=transforms)
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl  = DataLoader(ds_test,  batch_size=1024)

# Modelo, optimizador y loss
model = MiAlexNet().cuda()
optimizer = Adam(model.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

# Entrenamiento
model.train()
for epoch in range(1, 11):
    total_correctas = total_muestras = 0.0
    for x, target in train_dl:
        optimizer.zero_grad()
        x, target = x.cuda(), target.cuda()
        output = model(x)
        loss = loss_function(output, target)
        loss.backward()
        optimizer.step()
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
    print(f"Epoca {epoch}: Train Accuracy {100*total_correctas/total_muestras:.2f}%")

# Evaluacion en test
model.eval()
total_correctas = total_muestras = 0.0
with torch.no_grad():
    for x, target in test_dl:
        x, target = x.cuda(), target.cuda()
        output = model(x)
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
print(f"Test Accuracy: {100*total_correctas/total_muestras:.2f}%")


Epoca 1: Train Accuracy 3.18%
Epoca 2: Train Accuracy 4.15%
Epoca 3: Train Accuracy 5.86%
Epoca 4: Train Accuracy 6.88%
Epoca 5: Train Accuracy 7.51%
Epoca 6: Train Accuracy 10.16%
Epoca 7: Train Accuracy 13.57%
Epoca 8: Train Accuracy 16.12%
Epoca 9: Train Accuracy 19.82%
Epoca 10: Train Accuracy 23.69%
Test Accuracy: 22.15%


**Respuesta 1:**

¿Qué resultados obtiene en train y test?

Train: 23.69%
Test: 22.15%


**Actividad 2**

In [50]:
class MiAlexNetDropout(nn.Module):
    def __init__(self):
        super(MiAlexNetDropout, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=96, kernel_size=(11,11), stride=(4,4), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=96, out_channels=256, kernel_size=(5,5), stride=(1,1), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(in_channels=256, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv4 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv5 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=256, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.flat = nn.Flatten()

        self.fc6 = nn.Sequential(
            nn.Dropout(),               # ← ACTIVADO (p=0.5 por defecto)
            nn.Linear(9216, 4096),
            nn.ReLU()
        )
        self.fc7 = nn.Sequential(
            nn.Dropout(),               # ← ACTIVADO (p=0.5 por defecto)
            nn.Linear(4096, 4096),
            nn.ReLU()
        )
        self.fc8 = nn.Sequential(
            nn.Linear(4096, 102)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)
        return x

In [51]:
# Entrenamiento (identico al anterior, solo cambia el modelo)
model2 = MiAlexNetDropout().cuda()
optimizer = Adam(model2.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

model2.train()
for epoch in range(1, 11):
    total_correctas = total_muestras = 0.0
    for x, target in train_dl:
        optimizer.zero_grad()
        x, target = x.cuda(), target.cuda()
        output = model2(x)
        loss = loss_function(output, target)
        loss.backward()
        optimizer.step()
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
    print(f"Epoca {epoch}: Train Accuracy {100*total_correctas/total_muestras:.2f}%")

Epoca 1: Train Accuracy 3.04%
Epoca 2: Train Accuracy 2.76%
Epoca 3: Train Accuracy 3.01%
Epoca 4: Train Accuracy 3.32%
Epoca 5: Train Accuracy 3.09%
Epoca 6: Train Accuracy 2.99%
Epoca 7: Train Accuracy 3.45%
Epoca 8: Train Accuracy 4.69%
Epoca 9: Train Accuracy 5.94%
Epoca 10: Train Accuracy 6.33%


In [52]:
# Test
model2.eval()
total_correctas = total_muestras = 0.0
with torch.no_grad():
    for x, target in test_dl:
        x, target = x.cuda(), target.cuda()
        output = model2(x)
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
print(f"Test Accuracy: {100*total_correctas/total_muestras:.2f}%")

Test Accuracy: 7.25%


Respuesta 2:

Sí, y muy diferentes


Sin Dropout:   epoch 10 → 26.13%
Con Dropout:   epoch 10 →  6.33%

El rendimiento cae mucho — pero no porque el dropout sea malo, sino porque 10 epochs no es suficiente con p=0.5.

El dropout apaga el 50% de las 4096 neuronas de fc6 y fc7 en cada paso. La red aprende muchísimo más lento. En las primeras 7 epochs se queda básicamente en valores aleatorios (~1-3%), y recién en la epoch 8 empieza a despegar.

Creo que necesita mucho más que 10 epocas. Con 10 epochs y 5,687 imágenes el modelo sin dropout ni siquiera llega a overfittear, así que el regularizador llega antes de que haya un problema que resolver.

**Actividad 3**

In [53]:
class MiAlexNetBN(nn.Module):
    def __init__(self):
        super(MiAlexNetBN, self).__init__()

        # Conv1 y Conv2 sin cambios
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=96, kernel_size=(11,11), stride=(4,4), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=96, out_channels=256, kernel_size=(5,5), stride=(1,1), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )

        # Conv3, Conv4, Conv5 con BatchNorm ANTES de la convolucion
        self.conv3 = nn.Sequential(
            nn.BatchNorm2d(256),    # ← normaliza los 256 canales que vienen de conv2
            nn.Conv2d(in_channels=256, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv4 = nn.Sequential(
            nn.BatchNorm2d(384),    # ← normaliza los 384 canales que vienen de conv3
            nn.Conv2d(in_channels=384, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv5 = nn.Sequential(
            nn.BatchNorm2d(384),    # ← normaliza los 384 canales que vienen de conv4
            nn.Conv2d(in_channels=384, out_channels=256, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )

        self.flat = nn.Flatten()
        self.fc6 = nn.Sequential(nn.Linear(9216, 4096), nn.ReLU())
        self.fc7 = nn.Sequential(nn.Linear(4096, 4096), nn.ReLU())
        self.fc8 = nn.Sequential(nn.Linear(4096, 102))

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)
        return x

In [54]:
# Entrenamiento
model3 = MiAlexNetBN().cuda()
optimizer = Adam(model3.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

model3.train()
for epoch in range(1, 11):
    total_correctas = total_muestras = 0.0
    for x, target in train_dl:
        optimizer.zero_grad()
        x, target = x.cuda(), target.cuda()
        output = model3(x)
        loss = loss_function(output, target)
        loss.backward()
        optimizer.step()
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
    print(f"Epoca {epoch}: Train Accuracy {100*total_correctas/total_muestras:.2f}%")


Epoca 1: Train Accuracy 3.78%
Epoca 2: Train Accuracy 9.25%
Epoca 3: Train Accuracy 16.41%
Epoca 4: Train Accuracy 21.38%
Epoca 5: Train Accuracy 25.25%
Epoca 6: Train Accuracy 30.65%
Epoca 7: Train Accuracy 34.92%
Epoca 8: Train Accuracy 38.95%
Epoca 9: Train Accuracy 42.94%
Epoca 10: Train Accuracy 47.07%


In [55]:
# Test
model3.eval()
total_correctas = total_muestras = 0.0
with torch.no_grad():
    for x, target in test_dl:
        x, target = x.cuda(), target.cuda()
        output = model3(x)
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
print(f"Test Accuracy: {100*total_correctas/total_muestras:.2f}%")

Test Accuracy: 35.56%


**Respuesta 3**

Sí, un cambio enorme. BatchNorm casi duplica la accuracy en los mismos 10 epochs:


Sin BatchNorm:   epoch 10 → 26.13%
Con BatchNorm:   epoch 10 → 47.07%

El cambio más revelador es la velocidad de aprendizaje:

Epoch 1:   3.78%   → arranque similar
Epoch 2:   9.25%   → ya dobla al modelo base en epoch 2
Epoch 5:  25.25%   → ya igualó lo que el base logró en epoch 10
Epoch 10: 47.07%   → todavía subiendo con fuerza

El modelo sin BatchNorm llega a 26% y se empieza a estancar.

La razón: BatchNorm normaliza las activaciones entre capas, lo que hace que los gradientes fluyan de forma estable hacia las capas iniciales. La red puede dar pasos de aprendizaje más grandes sin desestabilizarse, y aprende más en cada epoch.

Actividad 4

In [58]:
# Ponga su código aquí
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet
from torchvision.transforms import Compose, Resize, ToTensor

# Datos
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms)
ds_test  = Flowers("flowers_dataset/test",  transform=transforms)
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl  = DataLoader(ds_test,  batch_size=1024)

# Modelo preentrenado
model4 = alexnet(pretrained=True)
model4.features.requires_grad_(False)   # congela los bloques conv (no se entrenan)
model4.classifier = nn.Sequential(      # reemplaza el clasificador para 102 clases
    nn.Dropout(),
    nn.Linear(256 * 6 * 6, 4096),
    nn.ReLU(inplace=True),
    nn.Dropout(),
    nn.Linear(4096, 4096),
    nn.ReLU(inplace=True),
    nn.Linear(4096, 102),
)
model4 = model4.cuda()

optimizer     = Adam(model4.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

# Entrenamiento
model4.train()
for epoch in range(1, 11):
    total_correctas = total_muestras = 0.0
    for x, target in train_dl:
        optimizer.zero_grad()
        x, target = x.cuda(), target.cuda()
        output = model4(x)
        loss   = loss_function(output, target)
        loss.backward()
        optimizer.step()
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
    print(f"Epoca {epoch}: Train Accuracy {100*total_correctas/total_muestras:.2f}%")

Epoca 1: Train Accuracy 21.47%
Epoca 2: Train Accuracy 51.84%
Epoca 3: Train Accuracy 63.57%
Epoca 4: Train Accuracy 70.12%
Epoca 5: Train Accuracy 74.50%
Epoca 6: Train Accuracy 78.39%
Epoca 7: Train Accuracy 80.94%
Epoca 8: Train Accuracy 81.52%
Epoca 9: Train Accuracy 82.93%
Epoca 10: Train Accuracy 84.16%


In [59]:
# Evaluacion en test
model4.eval()
total_correctas = total_muestras = 0.0
with torch.no_grad():
    for x, target in test_dl:
        x, target = x.cuda(), target.cuda()
        output = model4(x)
        total_correctas += (output.argmax(dim=1) == target).sum()
        total_muestras  += target.shape[0]
print(f"Test Accuracy: {100*total_correctas/total_muestras:.2f}%")

Test Accuracy: 76.47%


**Respuesta 4:**

Sí. El Transfer Learning es impresionante.

Epoch 1: 21.47% — arranca ya por encima de donde el modelo base termina después de 10 epochs (26%).

Epoch 10: 84.16% — más de 3 veces el modelo base.


Act.1 Sin modificar:   26%
Act.4 Transfer:        84%

La diferencia es que no está aprendiendo desde cero.
